name: UltimateUserInterface
version: '${version}'
main: self.starvern.ultimateuserinterface.UUI
api-version: 1.19
authors: [ Starvern ]
description: An advanced GUI management system for ease-of-use.
commands:
  interface:
    description: Open a gui
    aliases: [if]